[pytest]
; 自动识别用例
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = cases

; 命令行参数 —— 让报告显示完整详情
addopts = 
    -v
    -s
    --tb=short
    --capture=no
    --html=report/report.html
    --self-contained-html
    --alluredir=report/allure-result
    --clean-alluredir
    --log-cli-level=INFO

; 编码
console_output_style = classic