# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['gui.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('cases', 'cases'),
        ('base', 'base'),
        ('core', 'core'),
        ('pages', 'pages'),
        ('utils', 'utils'),
        ('config', 'config'),
        ('data', 'data'),
        ('run.py', '.')
    ],
    hiddenimports=[
        # === 核心依赖 ===
        'requests',
        'selenium',
        'pytest',
        'psutil',
        'winreg',
        'webdriver_manager',
        'pyautogui',
        'pynput',
        'PIL',
        'PIL.Image',
        'PIL.ImageGrab',
        'mouseinfo',
        'selenium.webdriver.common.action_chains',
        'selenium.webdriver.common.keys',
        'selenium.webdriver.common.by',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'selenium.webdriver.common.desired_capabilities',
        'selenium.webdriver.chrome.webdriver',
        'selenium.webdriver.remote.webelement',
        'selenium.webdriver.remote.command',
        'selenium.webdriver.remote.errorhandler',
        'selenium.webdriver.remote.remote_connection',
        'selenium.webdriver.remote.utils',
        'selenium.common.exceptions',

        # === Requests 依赖 ===
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',

        # === Selenium 完整依赖 ===
        'selenium.webdriver.common.by',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.chrome.options',
        'selenium.webdriver.edge.service',
        'selenium.webdriver.edge.options',
        'selenium.webdriver.firefox.service',
        'selenium.webdriver.firefox.options',
        'webdriver_manager.chrome',
        'webdriver_manager.core',

        # === pytest 核心完整模块 ===
        'pytest',
        '_pytest',
        '_pytest.config',
        '_pytest.main',
        '_pytest.python',
        '_pytest.terminal',
        '_pytest.runner',
        '_pytest.reports',
        '_pytest.collect',
        '_pytest.hookspec',
        '_pytest.fixtures',
        '_pytest.assertion',
        '_pytest.outcomes',
        '_pytest.junitxml',
        'pytest._argcomplete',

        # === pytest 插件系统 ===
        'pluggy',
        'pluggy._manager',
        'pluggy._hooks',

        # === pytest 基础依赖 ===
        'attrs',
        'attr',
        'py',
        'wcwidth',
        'colorama',
        'iniconfig',
        'tomli',
        'toml',
        'packaging',
        'pyparsing',
        'more_itertools',
        'importlib_metadata',
        'zipp',
        'typing_extensions',

        # === pytest-html 报告完整依赖（关键！） ===
        'pytest_html',
        'pytest_html.plugin',
        'pytest_html.utils',
        'pytest_html.result',
        'pytest_html.extras',
        'jinja2',
        'jinja2.ext',
        'jinja2.compiler',
        'jinja2.runtime',
        'jinja2.nodes',
        'jinja2.lexer',
        'jinja2.parser',
        'jinja2.environment',
        'jinja2.loaders',
        'jinja2.bccache',
        'markupsafe',

        # === 报告解析 ===
        'xml.etree.ElementTree',
        'xml.dom.minidom',

        # === 元数据插件 ===
        'pytest_metadata',
        'pytest_metadata.plugin',

        # === 系统基础模块（保险） ===
        'json',
        'yaml',
        'os',
        'sys',
        'subprocess',
        'threading',
        'tkinter',
        'tkinter.scrolledtext',
        'tkinter.messagebox',
        'tkinter.ttk',
        'pathlib',
        'shutil',
        'webbrowser',
        'traceback',
        'logging',
        'datetime',
        'time',
        'collections',
        'functools',
        'operator',
        'io',
        'warnings',
        're',
        'string',
        'textwrap',
        'inspect',
        'ast',
        'codecs',
        'encodings',
        'encodings.utf_8',
        'encodings.latin_1',
        'encodings.cp1252',
        'encodings.ascii',
        'encodings.idna',

        # === 新增补充（解决打包后缺失） ===
        'types',                      # 用于创建 mock 模块
        'pynput.mouse',
        'pynput.keyboard',
        'pynput._util',
        'pynput.mouse._util',
        'pynput.keyboard._util',
        'PIL._imaging',
        'PIL._imagingft',
        'PIL._tkinter_finder',
        'selenium.webdriver.common.service',
        'selenium.webdriver.common.options',
        'selenium.webdriver.remote.webdriver',
        'selenium.webdriver.remote.switch_to',
        'selenium.webdriver.support.event_firing_webdriver',
        'selenium.webdriver.common.log',
        'webdriver_manager.drivers.chrome',
        'webdriver_manager.drivers.edge',
        'webdriver_manager.drivers.firefox',
        'webdriver_manager.core.download_manager',
        'webdriver_manager.core.file_manager',
        'webdriver_manager.core.logger',
        'webdriver_manager.core.os_manager',
        'webdriver_manager.core.utils',
        'webdriver_manager.microsoft',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Web端自动化测试工具',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,       # 无控制台窗口（纯 GUI）
    onefile=True,        # ★ 单文件打包模式 ★
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None
)